package telegram

//goland:noinspection GoUnusedConst
const (
	Name    = "Telegram Bots API"
	Version = "9.3.0"

	ParseModeMarkdown   = "Markdown"
	ParseModeMarkdownV2 = "MarkdownV2"
	ParseModeHTML       = "HTML"

	ChatTypeSender     = "sender"
	ChatTypePrivate    = "private"
	ChatTypeGroup      = "group"
	ChatTypeSupergroup = "supergroup"
	ChatTypeChannel    = "channel"

	MessageEntityTypeMention       = "mention"
	MessageEntityTypeHashtag       = "hashtag"
	MessageEntityTypeCashtag       = "cashtag"
	MessageEntityTypeBotCommand    = "bot_command"
	MessageEntityTypeUrl           = "url"
	MessageEntityTypeEmail         = "email"
	MessageEntityTypePhoneNumber   = "phone_number"
	MessageEntityTypeBold          = "bold"
	MessageEntityTypeItalic        = "italic"
	MessageEntityTypeUnderline     = "underline"
	MessageEntityTypeStrikethrough = "strikethrough"
	MessageEntityTypeSpoiler       = "spoiler"
	MessageEntityTypeCode          = "code"
	MessageEntityTypePre           = "pre"
	MessageEntityTypeTextLink      = "text_link"
	MessageEntityTypeTextMention   = "text_mention"
	MessageEntityTypeCustomEmoji   = "custom_emoji"

	ChatMemberStatusCreator       = "creator"
	ChatMemberStatusAdministrator = "administrator"
	ChatMemberStatusMember        = "member"
	ChatMemberStatusRestricted    = "restricted"
	ChatMemberStatusLeft          = "left"
	ChatMemberStatusKicked        = "kicked"

	MaskPositionPointForehead = "forehead"
	MaskPositionPointEyes     = "eyes"
	MaskPositionPointMouth    = "mouth"
	MaskPositionPointChin     = "chin"

	ChatActionTyping          = "typing"
	ChatActionUploadPhoto     = "upload_photo"
	ChatActionRecordVideo     = "record_video"
	ChatActionUploadVideo     = "upload_video"
	ChatActionRecordAudio     = "record_audio"
	ChatActionUploadAudio     = "upload_audio"
	ChatActionUploadDocument  = "upload_document"
	ChatActionChooseSticker   = "choose_sticker"
	ChatActionFindLocation    = "find_location"
	ChatActionRecordVideoNote = "record_video_note"
	ChatActionUploadVideoNote = "upload_video_note"

	UpdatesAllowedMessage            = "message"
	UpdatesAllowedEditedMessage      = "edited_message"
	UpdatesAllowedChannelPost        = "channel_post"
	UpdatesAllowedEditedChannelPost  = "edited_channel_post"
	UpdatesAllowedInlineQuery        = "inline_query"
	UpdatesAllowedChosenInlineResult = "chosen_inline_result"
	UpdatesAllowedCallbackQuery      = "callback_query"
	UpdatesAllowedShippingQuery      = "shipping_query"
	UpdatesAllowedPreCheckoutQuery   = "pre_checkout_query"

	InlineQueryResultTypeArticle  = "article"
	InlineQueryResultTypePhoto    = "photo"
	InlineQueryResultTypeGif      = "gif"
	InlineQueryResultTypeMpeg4Gif = "mpeg4_gif"
	InlineQueryResultTypeVideo    = "video"
	InlineQueryResultTypeAudio    = "audio"
	InlineQueryResultTypeVoice    = "voice"
	InlineQueryResultTypeDocument = "document"
	InlineQueryResultTypeLocation = "location"
	InlineQueryResultTypeVenue    = "venue"
	InlineQueryResultTypeContact  = "contact"
	InlineQueryResultTypeGame     = "game"

	EncryptedPassportElementTypePersonalDetails       = "personal_details"
	EncryptedPassportElementTypePassport              = "passport"
	EncryptedPassportElementTypeDriverLicense         = "driver_license"
	EncryptedPassportElementTypeIdentityCard          = "identity_card"
	EncryptedPassportElementTypeInternalPassport      = "internal_passport"
	EncryptedPassportElementTypeAddress               = "address"
	EncryptedPassportElementTypeUtilityBill           = "utility_bill"
	EncryptedPassportElementTypeBankStatement         = "bank_statement"
	EncryptedPassportElementTypeRentalAgreement       = "rental_agreement"
	EncryptedPassportElementTypePassportRegistration  = "passport_registration"
	EncryptedPassportElementTypeTemporaryRegistration = "temporary_registration"
	EncryptedPassportElementTypePhoneNumber           = "phone_number"
	EncryptedPassportElementTypeEmail                 = "email"

	StickerTypeRegular     = "regular"
	StickerTypeMask        = "mask"
	StickerTypeCustomEmoji = "custom_emoji"
)
