package telegram

const Name = "Telegram Bot API"
const Version = "6.3.0"

const ParseModeMarkdown = "Markdown"
const ParseModeMarkdownV2 = "MarkdownV2"
const ParseModeHTML = "HTML"

const ChatTypeSender = "sender"
const ChatTypePrivate = "private"
const ChatTypeGroup = "group"
const ChatTypeSupergroup = "supergroup"
const ChatTypeChannel = "channel"

const MessageEntityTypeMention = "mention"
const MessageEntityTypeHashtag = "hashtag"
const MessageEntityTypeCashtag = "cashtag"
const MessageEntityTypeBotCommand = "bot_command"
const MessageEntityTypeUrl = "url"
const MessageEntityTypeEmail = "email"
const MessageEntityTypePhoneNumber = "phone_number"
const MessageEntityTypeBold = "bold"
const MessageEntityTypeItalic = "italic"
const MessageEntityTypeUnderline = "underline"
const MessageEntityTypeStrikethrough = "strikethrough"
const MessageEntityTypeSpoiler = "spoiler"
const MessageEntityTypeCode = "code"
const MessageEntityTypePre = "pre"
const MessageEntityTypeTextLink = "text_link"
const MessageEntityTypeTextMention = "text_mention"
const MessageEntityTypeCustomEmoji = "custom_emoji"

const ChatMemberStatusCreator = "creator"
const ChatMemberStatusAdministrator = "administrator"
const ChatMemberStatusMember = "member"
const ChatMemberStatusRestricted = "restricted"
const ChatMemberStatusLeft = "left"
const ChatMemberStatusKicked = "kicked"

const MaskPositionPointForehead = "forehead"
const MaskPositionPointEyes = "eyes"
const MaskPositionPointMouth = "mouth"
const MaskPositionPointChin = "chin"

const ChatActionTyping = "typing"
const ChatActionUploadPhoto = "upload_photo"
const ChatActionRecordVideo = "record_video"
const ChatActionUploadVideo = "upload_video"
const ChatActionRecordAudio = "record_audio"
const ChatActionUploadAudio = "upload_audio"
const ChatActionUploadDocument = "upload_document"
const ChatActionChooseSticker = "choose_sticker"
const ChatActionFindLocation = "find_location"
const ChatActionRecordVideoNote = "record_video_note"
const ChatActionUploadVideoNote = "upload_video_note"

const UpdatesAllowedMessage = "message"
const UpdatesAllowedEditedMessage = "edited_message"
const UpdatesAllowedChannelPost = "channel_post"
const UpdatesAllowedEditedChannelPost = "edited_channel_post"
const UpdatesAllowedInlineQuery = "inline_query"
const UpdatesAllowedChosenInlineResult = "chosen_inline_result"
const UpdatesAllowedCallbackQuery = "callback_query"
const UpdatesAllowedShippingQuery = "shipping_query"
const UpdatesAllowedPreCheckoutQuery = "pre_checkout_query"

const InlineQueryResultTypeArticle = "article"
const InlineQueryResultTypePhoto = "photo"
const InlineQueryResultTypeGif = "gif"
const InlineQueryResultTypeMpeg4Gif = "mpeg4_gif"
const InlineQueryResultTypeVideo = "video"
const InlineQueryResultTypeAudio = "audio"
const InlineQueryResultTypeVoice = "voice"
const InlineQueryResultTypeDocument = "document"
const InlineQueryResultTypeLocation = "location"
const InlineQueryResultTypeVenue = "venue"
const InlineQueryResultTypeContact = "contact"
const InlineQueryResultTypeGame = "game"

const EncryptedPassportElementTypePersonalDetails = "personal_details"
const EncryptedPassportElementTypePassport = "passport"
const EncryptedPassportElementTypeDriverLicense = "driver_license"
const EncryptedPassportElementTypeIdentityCard = "identity_card"
const EncryptedPassportElementTypeInternalPassport = "internal_passport"
const EncryptedPassportElementTypeAddress = "address"
const EncryptedPassportElementTypeUtilityBill = "utility_bill"
const EncryptedPassportElementTypeBankStatement = "bank_statement"
const EncryptedPassportElementTypeRentalAgreement = "rental_agreement"
const EncryptedPassportElementTypePassportRegistration = "passport_registration"
const EncryptedPassportElementTypeTemporaryRegistration = "temporary_registration"
const EncryptedPassportElementTypePhoneNumber = "phone_number"
const EncryptedPassportElementTypeEmail = "email"

const StickerTypeRegular = "regular"
const StickerTypeMask = "mask"
const StickerTypeCustomEmoji = "custom_emoji"
